name: aries_design_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # Use the pinned version from flutter_localizations
  latlong2: ^0.9.0 # 用于地图坐标
  flutter_map: ^5.0.0 # 用于地图
  geolocator: ^9.0.2 # 用于定位
  url_launcher: ^6.1.12 # 用于打开外部链接
  app_settings: ^5.0.0 # 用于打开系统设置
  provider: ^6.0.1 #状态管理
  logger: ^2.0.1 #日志
  flutter_bloc: ^8.1.3 # 用于使用bloc
  vector_math: ^2.1.0
  http: ^1.1.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  integration_test: # 用于集成测试
    sdk: flutter 
  flutter_test: # 用于单元测试
    sdk: flutter
flutter:
  generate: true

  assets:
    - fonts/icon/iconfont.ttf

  fonts:
      - family: AriIcons
        fonts:
          - asset: fonts/icon/iconfont.ttf
