name: aries_design_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # Use the pinned version from flutter_localizations
  latlong2: ^0.8.1
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  url_launcher: ^6.1.12
  app_settings: ^5.0.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  generate: true

  assets:
    - lib/fonts/icon/iconfont.ttf

  fonts:
      - family: AriIcons
        fonts:
          - asset: lib/fonts/icon/iconfont.ttf
